package view;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author Nazli
 */
public class DormListWindow extends javax.swing.JFrame {

	/**
	 * Creates new form DormWindow
	 */
	public DormListWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		dormListWindowPanel = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		JLabel label = new JLabel("Dorm List");
		label.setFont(new Font("Tahoma", Font.BOLD, 12));
		
		JScrollPane scrollPane = new JScrollPane();

		javax.swing.GroupLayout gl_dormWindowPanel = new javax.swing.GroupLayout(
				dormListWindowPanel);
		gl_dormWindowPanel.setHorizontalGroup(
			gl_dormWindowPanel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_dormWindowPanel.createSequentialGroup()
					.addGap(35)
					.addGroup(gl_dormWindowPanel.createParallelGroup(Alignment.TRAILING)
						.addComponent(scrollPane, Alignment.LEADING)
						.addComponent(label, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(152, Short.MAX_VALUE))
		);
		gl_dormWindowPanel.setVerticalGroup(
			gl_dormWindowPanel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_dormWindowPanel.createSequentialGroup()
					.addGap(18)
					.addComponent(label, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
					.addGap(13)
					.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
					.addContainerGap())
		);
		String dorm[] = {"a","b", "c", "d0", "e"};
		JList list = new JList(dorm);
		scrollPane.setViewportView(list);
		dormListWindowPanel.setLayout(gl_dormWindowPanel);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				dormListWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				dormListWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private javax.swing.JPanel dormListWindowPanel;
}
