/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import background.Dorm;
import background.Room;
import database.DBConnection;

/**
 *
 * @author Nazli
 */
public class RoomWindow extends javax.swing.JFrame {

	/**
	 * Creates new form StudentWindow
	 */
	public RoomWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		dormAddDutton = new javax.swing.JButton();
		roomDormNumberLabel = new javax.swing.JLabel();
		roomRoomNumberLabel = new javax.swing.JLabel();
		roomRoomTypeLabel = new javax.swing.JLabel();
		roomDormNumberText = new javax.swing.JTextField();
		roomRoomNumberText = new javax.swing.JTextField();
		roomRoomTypeText = new javax.swing.JTextField();
		roomRoomPriceText = new javax.swing.JTextField();
		roomAddButton = new javax.swing.JButton();
		roomRoomPriceLabel = new javax.swing.JLabel();

		dormAddDutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		dormAddDutton.setText("ADD");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		roomDormNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		roomDormNumberLabel.setText("Dorm Number:");

		roomRoomNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		roomRoomNumberLabel.setText("Room Number:");

		roomRoomTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		roomRoomTypeLabel.setText("Room Type:");
		roomRoomPriceText.setEditable(false);

		roomAddButton.setBackground(new java.awt.Color(204, 255, 204));
		roomAddButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		roomAddButton.setText("ADD");
		roomAddButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					addRoomButtonActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		roomRoomPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		roomRoomPriceLabel.setText("Room Price:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						roomDormNumberLabel,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						roomRoomNumberLabel,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						103,
																						Short.MAX_VALUE)
																				.addComponent(
																						roomRoomTypeLabel,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						roomRoomPriceLabel,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						roomRoomTypeText,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						115,
																						Short.MAX_VALUE)
																				.addComponent(
																						roomDormNumberText,
																						javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						roomRoomNumberText,
																						javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						roomRoomPriceText)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		roomAddButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		66,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(22, 22, 22)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														roomDormNumberLabel)
																												.addComponent(
																														roomDormNumberText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(21,
																										21,
																										21)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														roomRoomNumberText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														roomRoomNumberLabel))
																								.addGap(22,
																										22,
																										22)
																								.addComponent(
																										roomRoomTypeText,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						roomRoomTypeLabel))
																.addGap(24, 24,
																		24)
																.addComponent(
																		roomRoomPriceText,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														roomRoomPriceLabel))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										18, Short.MAX_VALUE)
								.addComponent(roomAddButton).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt)
			throws SQLException {
		if (roomRoomNumberText.getText().isEmpty()) {
			JOptionPane.showMessageDialog(getContentPane(),
					"The mandatory field is empty, please fill");
		} else {
			Room room = new Room();
			int roomNo = Integer.parseInt(roomRoomNumberText.getText());
			String roomType = roomRoomTypeText.getText();
			// Double roomPrice =
			// Double.parseDouble(roomRoomPriceText.getText());
			room.setRoomNo(roomNo);
			room.setTypeName(roomType);
			// room.setRoomPrice(roomPrice);
			System.out.println(roomNo);
			DBConnection connection = new DBConnection();
			if (connection.insertRoom(room)) {
				System.out.println("Kayit basarili");
			} else {
				System.out.println("Kayit basarisiz");
			}
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton roomAddButton;
	private javax.swing.JButton dormAddDutton;
	private javax.swing.JLabel roomDormNumberLabel;
	private javax.swing.JLabel roomRoomNumberLabel;
	private javax.swing.JLabel roomRoomTypeLabel;
	private javax.swing.JLabel roomRoomPriceLabel;
	private javax.swing.JTextField roomDormNumberText;
	private javax.swing.JTextField roomRoomNumberText;
	private javax.swing.JTextField roomRoomTypeText;
	private javax.swing.JTextField roomRoomPriceText;
	// End of variables declaration//GEN-END:variables
}
